export async function retryAsync<T>(
  fn: () => Promise<T>,
  retries: number,
): Promise<T> {
  try {
    return await fn()
  }
  catch (error: any) {
    if (retries > 0) {
      return retryAsync(fn, retries - 1)
    }
    else {
      throw error
    }
  }
}
